---
## tasks file for install_deployment_pre_requisites
- name: Install Java 8.
  become: yes
  apt:
    name: openjdk-8-jdk

- name: Set default Java version to Java 8.
  become: yes
  shell: 'sudo update-java-alternatives --set /usr/lib/jvm/java-1.8.0-openjdk-armhf'


- name: Check default Java version.
  shell: 'java -version'
  register: java_version_check_output

- debug:
    msg: "{{java_version_check_output}}"

- name: Installing maven.
  become: yes
  apt:
    name: maven

- name: Download and unarchive Arm7 supported version of node.
  become: yes
  unarchive:
    src: https://nodejs.org/dist/v14.16.0/node-v14.16.0-linux-armv7l.tar.xz
    dest: /tmp/
    remote_src: yes

- name: Copy all files of un-tared node package to /usr/local.
  become: yes
  copy:
    dest: /usr/local/
    src: /tmp/node-v14.16.0-linux-armv7l/
    mode: "777"
    remote_src: yes

- name: Get npm version
  shell: 'npm -v'
  register: npm_version

- debug:
    msg: "NPM version {{npm_version.stdout}}"

- name: Get node version
  shell: 'node -v'
  register: node_version

- debug:
    msg: "Node version {{node_version.stdout}}"

- name: Install angular cli globally using npm.
  become: yes
  shell: "npm install -g @angular/cli"

- name: Create directory to hold installed applications.
  become: yes
  file:
    path: /usr/local/applications
    state: directory
    mode: "777"

- name: Install Apache Tomcat 9 in directory /usr/local/applications
  become: yes
  unarchive:
    src: https://downloads.apache.org/tomcat/tomcat-9/v9.0.44/bin/apache-tomcat-9.0.44.tar.gz
    dest: /usr/local/applications/
    remote_src: yes
    mode: "777"

- name: Determine whether docker is installed yet. # Docs mentions that trying to install docker from the script if it has already been installed may cause issues.
  shell: 'docker -v'
  register: docker_version

- name: Gather host package installation facts to determine whether docker is installed.
  ansible.builtin.package_facts:
    strategy: all

- name: Download the docker install script.
  become: yes
  uri:
    url: https://get.docker.com
    dest: /tmp/
  when: "'docker-ce-cli' not in ansible_facts.packages"

- name: Execute the docker get-docker.sh script just downloaded to install docker.
  become: yes
  shell: sh /tmp/get-docker.sh
  when: "'docker-ce-cli' not in ansible_facts.packages"

- name: Pull RabbitMQ and its Management image, expose ports and run the image.
  become: yes
  shell: "docker run -d --hostname local-rabbitmq --name control-hub-rmq -p 15672:15672 -p 5672:5672 rabbitmq:3.8.14-management"


