---
# tasks file for create_control_hub_service
- name: Create a systemd service of the control-hub backend.
  become: yes
  template:
    src: service.j2
    dest: "{{base_services_location}}/control-hub-backend.service"
    owner: root
    mode: "777"
