---
# tasks file for create_control_hub_service
- name: Clear previous control-hub-backend service
  include_role:
    name: clear_previous_service
  vars:
    - service_name: "control-hub-backend"

- name: Create a systemd service of the control-hub backend.
  become: yes
  template:
    src: service.j2
    dest: "{{base_services_location}}/control-hub-backend.service"
    owner: root
    mode: "777"

- name: Reload the systemd daemon, ensuring changes to to unit files take proper effect.
  become: yes
  systemd:
    daemon_reload: yes
