---
- name: Install Java 8.
  become: yes
  apt:
    name: openjdk-8-jdk

- name: Set default Java version to Java 8.
  become: yes
  shell: 'sudo update-java-alternatives --set /usr/lib/jvm/java-1.8.0-openjdk-armhf'