server:
  port: 8081

spring:
  rabbitmq:
    port: 5672
    host: 192.168.0.130
  cloud:
    stream:
      bindings:
        input:
          destination: pumpconfigupdate

control-hub:
  host: 192.168.0.130
  port: 8080
