server:
  port: 8081

spring:
  rabbitmq:
    port: 5672
    host: 192.168.0.130

  cloud:
    stream:
      bindings:
        updatedPumpConfigInput:
          destination: pumpconfigupdate
        newTempOutput:
          destination: ambienttemp
        pumpControllerStateOutput:
          destination: pumpcontrollertogglestatus


control-hub:
  host: 192.168.0.130
  port: 8080

mcp3002:
  python-script:
    location: /scripts/mcp3002_adc_value.py

automatic-pump-toggler:
  readings-before-check: 5

ambient-temp-reader:
  scheduler:
    delay-seconds: 10
    rate-seconds: 20
