server:
  port: 8081

spring:
  rabbitmq:
    port: 5672
    host: localhost

  cloud:
    stream:
      bindings:
        updatedPumpConfigInput:
          destination: pumpconfigupdate
        newTempOutput:
          destination: ambienttemp
        pumpControllerStateOutput:
          destination: pumpcontrollertogglestatus


control-hub:
  host: localhost
  port: 8081

mcp3002:
  python-script:
    location: /usr/local/applications/Pump Controller/mcp3002_adc_value.py

# error of thermistor measured temperature in degrees celsius
temp-reading:
  error: 2

automatic-pump-toggler:
  readings-before-check: 5

ambient-temp-reader:
  scheduler:
    delay-seconds: 10
    rate-seconds: 5
