server:
  port: 8081
  servlet:
    context-path: "/control-hub-backend"
spring:
  rabbitmq:
    port: 5672
  cloud:
    stream:
      bindings:
        newPumpConfigOutput:
          destination: pumpconfigupdate
        newAmbientTempInput:
          destination: ambienttemp
        pumpStateInput:
          destination: pumpcontrollertogglestatus
pump-config-file-location: /usr/local/applications/Control Hub Backend/pump/pump_config.json
