---
# tasks file for deploy_control_hub
- name: Delete old deploy.
  become: yes
  file:
    path: "{{base_control_hub_deploy_location}}"
    state: absent

- name: Copying staged control-hub-ui component to /Desktop/Control Hub.
  become: yes
  copy:
    remote_src: yes # source is already on the host
    src: "{{base_control_hub_stage_location}}/IoT UI/control-hub-ui"
    dest: "{{base_control_hub_deploy_location}}"
- name: Copying staged control-hub backend component to /Desktop/Control Hub.
  become: yes
  copy:
    remote_src: yes
    src: "{{base_control_hub_stage_location}}/IoT UI/control-hub"
    dest: "{{base_control_hub_deploy_location}}"