---
- name: Clear previous pump-controller service
  include_role:
    name: "../Common/clear_previous_service"
  vars:
    - service_name: "pump-controller"

- name: Create a systemd service of the Pump Controller.
  become: yes
  template:
    src: service.j2
    dest: "{{base_services_location}}/pump-controller.service"
    owner: root
    mode: "777"

- name: Reload the systemd daemon, ensuring changes to unit files take proper effect.
  become: yes
  systemd:
    daemon_reload: yes
