server:
  port: 8080
  servlet:
    context-path: "/control-hub-backend"
spring:
  rabbitmq:
    port: 5672
  cloud:
    stream:
      bindings:
        output:
          destination: pumpconfigupdate
        input:
          destination: ambienttemp
