galaxy_info:
  author: PiAndArduinoGuy
  description: Copies the docker-start-sontrol-hub-rmq-container service file to the RaspberryPi
  license: license (GPL-2.0-or-later, MIT, etc)
  min_ansible_version: 2.9
  