galaxy_info:
  author: PiAndArduinoGuy
  description: Stops the service if needed, removes it form startup, deletes the service and reloads the daemon.
  license: license (GPL-2.0-or-later, MIT, etc)
  min_ansible_version: 2.9
  